let radius = parseFloat(prompt('Mời bạn hhập bán khính hình tròn'));
const PI = 3.14;
let diameter = 2*radius;
let C = diameter*2;
let S = (radius*radius)*PI;
document.write('Đường kính hình tròn là:'+' '+diameter);
document.write('<br>');
document.write('Chu vi hình tròn là:'+' '+C);
document.write('<br>');
document.write('Diện tích hình tròn là:'+' '+S);